
# Base zsh options
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
unsetopt beep

# Update settings
zstyle ':omz:update' mode auto

# Check for updates every 7 days
zstyle ':omz:update' frequency 7