# If not running interactively, don't do anything
# We might not need this 
[[ $- != *i* ]] && return


# Aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'

alias gc="git commit --verbose"
alias ga="git add"
alias gp="git push"


# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/jstiverson/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
